---

- name: Configure default prompt
  lineinfile:
    dest: "/etc/profile.d/default_prompt.sh"
    create: "yes"
    regexp: "^PS1="
    line: "PS1='\
      \\[\\033[01m\\]{{ inventory_hostname.split('.')[0] }}.{{ inventory_hostname.split('.')[1] }}\
      \\[\\033[00m\\]:\
      \\[\\033[01;34m\\]\\W \
      \\[\\033[00m\\]\\u\
      \\$ '
    "
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')

- name: Configure PATH /usr/local/bin for root
  lineinfile:
    dest: "/root/.bash_profile"
    create: "yes"
    regexp: "# add /usr/local/bin$"
    line: "export PATH=$PATH:/usr/local/bin # add /usr/local/bin"