---

- name: Add signing key
  rpm_key:
    key: "https://download.docker.com/linux/rhel/gpg"
    state: present

- name: Add repository into repo.d list
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Start Docker
  service:
    name: "docker"
    enabled: true
    state: started