- name: Setup host
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  ignore_unreachable: yes

  pre_tasks:
    - name: Gather facts ansible_*
      setup:
        filter: "ansible_*"
      tags: always

  tasks:
    - import_role:
        name: common
      tags: common

    - import_role:
        name: chrony
      tags: ntp

    - import_role:
        name: users
      tags: users

    - import_role:
        name: docker
      tags: docker

    - import_role:
        name: security
      tags: security

    - import_role:
        name: cronjobs
      tags: cronjobs

